# Generated by Django 2.1.2 on 2018-12-02 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_auto_20181202_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 20, 13, 24, 47220, tzinfo=utc)),
        ),
    ]
